# Generated by Django 5.0.4 on 2024-04-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('image', models.ImageField(upload_to='playlist/', verbose_name='Image')),
                ('number_of_videos', models.PositiveIntegerField(verbose_name='NumberOfVideos')),
            ],
        ),
    ]
