# Generated by Django 5.0.4 on 2024-05-06 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_delete_user_alter_playlist_channel'),
        ('user', '0004_alter_notification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_owner', to='user.user'),
        ),
    ]
