# Generated by Django 5.0.4 on 2024-05-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('channel_name', models.CharField(max_length=50, verbose_name='Channel Name')),
                ('channel_ava', models.ImageField(upload_to='user/', verbose_name='Ava')),
                ('number_of_videos', models.PositiveIntegerField(verbose_name='NumberOfVideos')),
                ('video_image', models.ImageField(upload_to='user/', verbose_name='Ava')),
                ('date', models.CharField(max_length=50, verbose_name='Date')),
            ],
        ),
    ]
