# Generated by Django 5.0.4 on 2024-05-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('image', models.ImageField(upload_to='video/', verbose_name='Image')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('replies_comment', models.PositiveIntegerField(max_length=1000, verbose_name='Comments')),
            ],
        ),
    ]
