# Generated by Django 5.0.4 on 2024-05-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replies_comment',
            field=models.TextField(max_length=1000, verbose_name='Comments'),
        ),
    ]
