# Generated by Django 5.0.4 on 2024-05-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_comment_video_alter_comment_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replies_comment',
            field=models.PositiveIntegerField(default=0, verbose_name='NumberOfComments'),
        ),
    ]
