# Generated by Django 5.0.4 on 2024-05-03 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_channel_video_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='user_name',
        ),
        migrations.AddField(
            model_name='video',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date'),
        ),
    ]
