# Generated by Django 5.0.4 on 2024-05-06 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_channel_owner'),
        ('video', '0003_remove_video_user_name_video_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_playlist', to='channel.playlist'),
        ),
    ]
